spring:
    application:
        name: knsgconference
    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/knsgconference
        username: ${DB_USER:postgres}
        password: ${DB_PASSWORD:postgres}
    jpa:
        hibernate:
            ddl-auto: create-drop